<?php

namespace AppBundle\Repository;

/**
 * NominesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NominesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllCategories(){
        $qb = $this->createQueryBuilder('c');
        $qb->orderby('c.id');
        $qb->groupby('c.id');

        return $qb->getQuery()
            ->getResult();
    }

    public function getCurrentYear()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->expr()->max('a.annee');
        return $qb->getQuery()
            ->getResult();

    }
}
